name: CI_iOS
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-and-test:
    runs-on: macos-13
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app

    - name: Build and test
      run: xcodebuild clean build test -project essential-feed-case-study.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro" ONLY_ACTIVE_ARCH=YES